# DB settings
dsn: postgres://postgres:T0psecret@postgres:5432/caro?sslmode=disable&pool_max_conns=3
gmt_timezone: 3
#TG settings
token: stub
admins: []
channel_id: 0
suggestions_id: 0
repost_period_sec: 3600
post_period_sec: 10800

# Flush settings
flush_period_sec: 86400
